# Generated by Django 6.0.6 on 2026-09-13 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('english_level', models.PositiveSmallIntegerField(choices=[(1, 'English 1'), (2, 'English 2'), (3, 'English 3'), (4, 'English 4'), (5, 'English 5')])),
                ('grammar_focus', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('introduction', models.TextField(blank=True, help_text='Introductory text shown before the adventure begins.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['english_level', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AdventureCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, help_text='Example: Engineer, Student, Security Officer.', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('perspective', models.TextField(blank=True, help_text='Information that should influence how this character approaches decisions.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='choose_adventure.adventurestory')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StoryStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160)),
                ('station_type', models.CharField(choices=[('STORY', 'Story Station'), ('ENDING', 'Ending')], default='STORY', max_length=20)),
                ('story_text', models.TextField()),
                ('is_start', models.BooleanField(default=False, help_text='Marks the first station of the adventure.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='choose_adventure.adventurestory')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoryChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('next_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_choices', to='choose_adventure.storystation')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='choose_adventure.storystation')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='storystation',
            constraint=models.UniqueConstraint(fields=('story', 'slug'), name='unique_station_slug_per_story'),
        ),
    ]
