# Generated by Django 6.0.6 on 2026-09-13 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_adventure', '0001_initial'),
        ('game_sessions', '0002_alter_participant_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_run', to='game_sessions.gamesession')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='choose_adventure.adventurestory')),
            ],
        ),
    ]
