# Generated by Django 6.0.6 on 2026-09-13 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_adventure', '0002_adventurerun'),
    ]

    operations = [
        migrations.AddField(
            model_name='storychoice',
            name='bio_horror_delta',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storychoice',
            name='containment_delta',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storychoice',
            name='cyberpunk_delta',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storychoice',
            name='forbidden_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='storychoice',
            name='humanity_delta',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storychoice',
            name='knowledge_delta',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storychoice',
            name='min_containment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storychoice',
            name='min_humanity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storychoice',
            name='min_knowledge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storychoice',
            name='required_dominant_genre',
            field=models.CharField(blank=True, choices=[('SCI_FI', 'Sci-Fi'), ('CYBERPUNK', 'Cyberpunk'), ('BIO_HORROR', 'Bio-Horror')], max_length=20),
        ),
        migrations.AddField(
            model_name='storychoice',
            name='required_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='storychoice',
            name='sci_fi_delta',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storychoice',
            name='set_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='storystation',
            name='advance_mode',
            field=models.CharField(choices=[('CHOICE', 'Player Choice'), ('AUTO', 'Automatic'), ('TERMINAL', 'Terminal')], default='CHOICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='storystation',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storystation',
            name='station_type',
            field=models.CharField(choices=[('STORY', 'Story Station'), ('SYSTEM', 'System Station'), ('ENDING', 'Ending')], default='STORY', max_length=20),
        ),
        migrations.CreateModel(
            name='AutomaticRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=150)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('dominant_genre', models.CharField(blank=True, choices=[('SCI_FI', 'Sci-Fi'), ('CYBERPUNK', 'Cyberpunk'), ('BIO_HORROR', 'Bio-Horror')], max_length=20)),
                ('min_containment', models.IntegerField(blank=True, null=True)),
                ('max_containment', models.IntegerField(blank=True, null=True)),
                ('min_humanity', models.IntegerField(blank=True, null=True)),
                ('max_humanity', models.IntegerField(blank=True, null=True)),
                ('min_knowledge', models.IntegerField(blank=True, null=True)),
                ('max_knowledge', models.IntegerField(blank=True, null=True)),
                ('required_flags', models.JSONField(blank=True, default=list)),
                ('forbidden_flags', models.JSONField(blank=True, default=list)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automatic_routes', to='choose_adventure.storystation')),
                ('target_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_automatic_routes', to='choose_adventure.storystation')),
            ],
            options={
                'ordering': ['-priority', 'id'],
            },
        ),
    ]
