# Generated by Django 6.0.6 on 2026-09-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_adventure', '0003_storychoice_bio_horror_delta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurestory',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional cover image shown in story selection and lobby.', null=True, upload_to='choose_adventure/story_covers/'),
        ),
    ]
