# Generated by Django 6.0.6 on 2026-09-13 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_adventure', '0004_adventurestory_cover_image'),
        ('game_sessions', '0002_alter_participant_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adventure_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='choose_adventure.adventurerun')),
                ('current_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_currently_here', to='choose_adventure.storystation')),
                ('selected_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='choose_adventure.adventurecharacter')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdventureTeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_team_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_team_membership', to='game_sessions.participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='choose_adventure.adventureteam')),
            ],
            options={
                'ordering': ['team__sort_order', 'participant__joined_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='adventureteam',
            constraint=models.UniqueConstraint(fields=('adventure_run', 'name'), name='unique_team_name_per_adventure_run'),
        ),
    ]
