# Generated by Django 6.0.6 on 2026-09-13 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_adventure', '0005_adventureteam_adventureteammembership_and_more'),
        ('game_sessions', '0002_alter_participant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventureteam',
            name='character_selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adventureteam',
            name='character_selected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adventure_character_selections', to='game_sessions.participant'),
        ),
    ]
