# Generated by Django 6.0.6 on 2026-09-13 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_adventure', '0006_adventureteam_character_selected_at_and_more'),
        ('game_sessions', '0002_alter_participant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurecharacter',
            name='portrait_image',
            field=models.ImageField(blank=True, help_text='Optional portrait shown during character selection and gameplay.', null=True, upload_to='choose_adventure/character_portraits/'),
        ),
        migrations.AddField(
            model_name='adventureteam',
            name='bio_horror_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adventureteam',
            name='containment_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adventureteam',
            name='cyberpunk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adventureteam',
            name='ending_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_finished_here', to='choose_adventure.storystation'),
        ),
        migrations.AddField(
            model_name='adventureteam',
            name='humanity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adventureteam',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adventureteam',
            name='knowledge_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adventureteam',
            name='sci_fi_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adventureteam',
            name='story_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='storystation',
            name='scene_image',
            field=models.ImageField(blank=True, help_text='Optional scene image shown when this station is active.', null=True, upload_to='choose_adventure/station_scenes/'),
        ),
        migrations.CreateModel(
            name='TeamDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adventure_team_decisions', to='game_sessions.participant')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_decisions', to='choose_adventure.storychoice')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_decisions', to='choose_adventure.storystation')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='choose_adventure.adventureteam')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
