# Generated by Django 6.0.6 on 2026-09-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_adventure', '0007_adventurecharacter_portrait_image_and_more'),
        ('game_sessions', '0002_alter_participant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teamdecision',
            constraint=models.UniqueConstraint(fields=('team', 'station'), name='one_decision_per_team_station'),
        ),
    ]
