# Generated by Django 6.0.6 on 2026-09-14 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choose_adventure', '0008_teamdecision_one_decision_per_team_station'),
        ('game_sessions', '0002_alter_participant_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventureWrittenResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adventure_written_responses', to='game_sessions.participant')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_responses', to='choose_adventure.storystation')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_responses', to='choose_adventure.adventureteam')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('team', 'participant', 'station'), name='one_written_response_per_student_station')],
            },
        ),
    ]
