# Generated by Django 6.0.6 on 2026-06-24 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('join_code', models.SlugField(blank=True, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('LOBBY', 'Lobby'), ('ACTIVE', 'Active'), ('ENDED', 'Ended')], default='LOBBY', max_length=20)),
                ('current_step', models.CharField(default='waiting', help_text='Used to route students to the correct game step.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('game_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='games.gametemplate')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='game_sessions.gamesession')),
            ],
            options={
                'unique_together': {('session', 'student_id')},
            },
        ),
    ]
