# Generated by Django 6.0.6 on 2026-06-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(condition=models.Q(('student_id', ''), _negated=True), fields=('session', 'student_id'), name='unique_student_id_per_session_when_provided'),
        ),
    ]
