# Generated by Django 6.0.6 on 2026-06-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('FANTASY_ROLES', 'Fantasy Roles'), ('CHOOSE_ADVENTURE', 'Choose Your Own Adventure'), ('TREASURE_HUNT', 'Treasure Hunt'), ('ROLE_PLAY', 'Role Play')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
