# Generated by Django 6.0.6 on 2026-09-01 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_sessions', '0002_alter_participant_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Role name, e.g. Detective, Customer, Manager.', max_length=120)),
                ('character_name', models.CharField(blank=True, help_text='Optional character identity.', max_length=120)),
                ('public_description', models.TextField(blank=True, help_text='Information that is safe for the student to reveal during the activity.')),
                ('private_briefing', models.TextField(blank=True, help_text='Information known only by this role.')),
                ('objective', models.TextField(blank=True, help_text='What this role is trying to accomplish.')),
                ('secret_information', models.TextField(blank=True, help_text='Optional secrets, evidence, motivations, or hidden constraints.')),
                ('useful_language', models.TextField(blank=True, help_text='Optional vocabulary, sentence starters, or language support.')),
                ('copies_available', models.PositiveIntegerField(default=1, help_text='How many students may receive this role during the same session.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RolePlaySituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('summary', models.TextField(blank=True, help_text='Short description shown to the teacher.')),
                ('student_briefing', models.TextField(blank=True, help_text='Information every student should know before the role play begins.')),
                ('teacher_notes', models.TextField(blank=True, help_text='Instructions visible only to the teacher.')),
                ('language_target', models.TextField(blank=True, help_text='Grammar, vocabulary, communicative function, or learning objective practiced in this situation.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_snapshot', models.JSONField(blank=True, default=dict)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleplay_assignments', to='game_sessions.participant')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='roleplay.rolecard')),
            ],
        ),
        migrations.CreateModel(
            name='RolePlayRecordTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('instructions', models.TextField(blank=True)),
                ('applies_to_all_roles', models.BooleanField(default=False, help_text='If checked, every role receives this document.')),
                ('is_required', models.BooleanField(default=False)),
                ('allow_multiple', models.BooleanField(default=False, help_text='Allows the student to create several entries, such as an interview log or transaction register.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('roles', models.ManyToManyField(blank=True, help_text='Leave empty when the document applies to all roles.', related_name='record_templates', to='roleplay.rolecard')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_templates', to='roleplay.roleplaysituation')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RolePlayRecordSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('is_submitted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_submissions', to='roleplay.roleassignment')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='roleplay.roleplayrecordtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='RolePlayRecordField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('field_type', models.CharField(choices=[('SHORT_TEXT', 'Short text'), ('LONG_TEXT', 'Long text'), ('NUMBER', 'Number'), ('CHOICE', 'Choice'), ('CHECKBOX', 'Checkbox')], default='SHORT_TEXT', max_length=20)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list, help_text='Used for Choice fields. Example: ["Yes", "No", "Unknown"]')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='roleplay.roleplayrecordtemplate')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RolePlayRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SETUP', 'Setup'), ('ASSIGNED', 'Roles Assigned'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished')], default='SETUP', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('game_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roleplay_run', to='game_sessions.gamesession')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='roleplay.roleplaysituation')),
            ],
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='roleplay.roleplayrun'),
        ),
        migrations.AddField(
            model_name='rolecard',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='roleplay.roleplaysituation'),
        ),
        migrations.CreateModel(
            name='RolePlayRecordResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='roleplay.roleplayrecordfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='roleplay.roleplayrecordsubmission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('submission', 'field'), name='unique_roleplay_field_response')],
            },
        ),
        migrations.AddConstraint(
            model_name='roleplayrecordsubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'template', 'sequence'), name='unique_roleplay_record_instance'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('run', 'participant'), name='unique_roleplay_assignment_per_participant'),
        ),
    ]
