# Generated by Django 6.0.6 on 2026-09-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_sessions', '0002_alter_participant_unique_together_and_more'),
        ('roleplay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roleassignment',
            name='unique_roleplay_assignment_per_participant',
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='round_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roleplayrun',
            name='current_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('run', 'participant', 'round_number'), name='unique_roleplay_assignment_per_participant_round'),
        ),
    ]
