# Generated by Django 6.0.6 on 2026-09-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay', '0002_remove_roleassignment_unique_roleplay_assignment_per_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleplayrecordsubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roleplayrecordsubmission',
            name='teacher_feedback',
            field=models.TextField(blank=True),
        ),
    ]
