# Generated by Django 6.0.6 on 2026-06-24 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='character_classes/default/')),
                ('female_image', models.ImageField(blank=True, null=True, upload_to='character_classes/female/')),
                ('male_image', models.ImageField(blank=True, null=True, upload_to='character_classes/male/')),
                ('max_life', models.PositiveIntegerField(default=10)),
                ('action_points', models.PositiveIntegerField(default=3)),
                ('attack', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ap_cost', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='fantasy_roles.characterclass')),
            ],
            options={
                'ordering': ['ap_cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassWeakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaknesses', to='fantasy_roles.characterclass')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100)),
                ('english_level', models.CharField(choices=[('LEVEL_1', "Level 1 - Can / Can't"), ('LEVEL_2', 'Level 2 - Simple Past'), ('LEVEL_3', 'Level 3 - Modal Verbs'), ('LEVEL_4', 'Level 4 - Infinitives and Gerunds'), ('LEVEL_5', 'Level 5 - Present Perfect / Communication Strategies')], default='LEVEL_2', max_length=20)),
                ('backstory', models.TextField()),
                ('current_life', models.PositiveIntegerField(default=10)),
                ('current_action_points', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_notes', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_characters', to='fantasy_roles.characterclass')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_character', to='game_sessions.participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_characters', to='game_sessions.gamesession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
