# Generated by Django 6.0.6 on 2026-06-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercharacter',
            name='visual_variant',
            field=models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male')], default='FEMALE', max_length=10),
        ),
    ]
