# Generated by Django 6.0.6 on 2026-06-24 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0002_playercharacter_visual_variant'),
        ('game_sessions', '0002_alter_participant_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdventuringParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_dm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dm_for_parties', to='fantasy_roles.playercharacter')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_parties', to='game_sessions.gamesession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party_membership', to='fantasy_roles.playercharacter')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='fantasy_roles.adventuringparty')),
            ],
            options={
                'ordering': ['order', 'joined_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='adventuringparty',
            constraint=models.UniqueConstraint(fields=('session', 'name'), name='unique_party_name_per_session'),
        ),
    ]
