# Generated by Django 6.0.6 on 2026-06-24 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0003_adventuringparty_partymember_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('kingdom', models.CharField(blank=True, help_text='Example: Mystopia, Marshlund, Pyroterra.', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dungeons/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DungeonRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=150)),
                ('room_type', models.CharField(choices=[('TRAP', 'Trap Room'), ('COMBAT', 'Combat Room'), ('TREASURE', 'Treasure Room'), ('BOSS', 'Boss Room'), ('SPECIAL', 'Special Room')], default='TRAP', max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, help_text='Difficulty value used for trap/combat checks.', null=True)),
                ('flavor_text', models.TextField(blank=True)),
                ('failure_text', models.TextField(blank=True)),
                ('damage_on_failure', models.PositiveIntegerField(blank=True, help_text='Optional explicit damage for combat rooms.', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dungeon_rooms/')),
                ('grid_row', models.PositiveSmallIntegerField(default=1)),
                ('grid_col', models.PositiveSmallIntegerField(default=1)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='fantasy_roles.dungeon')),
            ],
            options={
                'ordering': ['dungeon', 'number'],
            },
        ),
        migrations.CreateModel(
            name='DungeonRoomConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_connections', to='fantasy_roles.dungeon')),
                ('from_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='fantasy_roles.dungeonroom')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='fantasy_roles.dungeonroom')),
            ],
            options={
                'ordering': ['dungeon', 'from_room__number', 'to_room__number'],
            },
        ),
        migrations.CreateModel(
            name='PartyDungeonRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SELECTED', 'Selected'), ('ACTIVE', 'Active'), ('CLEARED', 'Cleared'), ('FAILED', 'Failed')], default='SELECTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_party_runs', to='fantasy_roles.dungeonroom')),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_runs', to='fantasy_roles.dungeon')),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dungeon_run', to='fantasy_roles.adventuringparty')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_dungeon_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dungeonroom',
            constraint=models.UniqueConstraint(fields=('dungeon', 'number'), name='unique_room_number_per_dungeon'),
        ),
        migrations.AddConstraint(
            model_name='dungeonroomconnection',
            constraint=models.UniqueConstraint(fields=('from_room', 'to_room'), name='unique_dungeon_room_connection'),
        ),
    ]
