# Generated by Django 6.0.6 on 2026-06-24 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0004_dungeon_dungeonroom_dungeonroomconnection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partydungeonrun',
            name='selected_by',
        ),
        migrations.AddField(
            model_name='dungeon',
            name='difficulty_rating',
            field=models.PositiveSmallIntegerField(default=3, help_text='Use a value from 1 to 5.'),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='final_boss_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='play_style',
            field=models.CharField(choices=[('COMBAT_HEAVY', 'Combat-heavy'), ('PUZZLE_HEAVY', 'Puzzle-heavy'), ('BALANCED', 'Balanced'), ('TREASURE_HEAVY', 'Treasure-heavy')], default='BALANCED', max_length=30),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='room_count',
            field=models.PositiveSmallIntegerField(default=9),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='treasure_room_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='partydungeonrun',
            name='selected_by_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_dungeon_runs', to='fantasy_roles.playercharacter'),
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='image',
            field=models.ImageField(blank=True, help_text='Dungeon cover image shown to students.', null=True, upload_to='dungeons/'),
        ),
        migrations.CreateModel(
            name='DungeonVocabularySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_level', models.CharField(choices=[('LEVEL_1', "Level 1 - Can / Can't"), ('LEVEL_2', 'Level 2 - Simple Past'), ('LEVEL_3', 'Level 3 - Modal Verbs'), ('LEVEL_4', 'Level 4 - Infinitives and Gerunds'), ('LEVEL_5', 'Level 5 - Present Perfect / Communication Strategies')], max_length=20)),
                ('useful_vocabulary', models.TextField(blank=True, help_text='One word or phrase per line is recommended.')),
                ('sentence_frames', models.TextField(blank=True, help_text='Example sentence starters or useful structures.')),
                ('teacher_notes', models.TextField(blank=True)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_sets', to='fantasy_roles.dungeon')),
            ],
            options={
                'ordering': ['dungeon', 'english_level'],
                'constraints': [models.UniqueConstraint(fields=('dungeon', 'english_level'), name='unique_vocabulary_set_per_dungeon_level')],
            },
        ),
    ]
