# Generated by Django 6.0.6 on 2026-06-24 20:24

import django.db.models.deletion
from django.db import migrations, models

def clear_existing_run_current_rooms(apps, schema_editor):
    PartyDungeonRun = apps.get_model("fantasy_roles", "PartyDungeonRun")
    PartyDungeonRun.objects.update(current_room=None)

class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0005_remove_partydungeonrun_selected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='combat_room_count',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='special_room_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='Usually 1 special mimic room.'),
        ),
        migrations.AddField(
            model_name='dungeon',
            name='trap_room_count',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        
        migrations.AlterField(
            model_name='partydungeonrun',
            name='status',
            field=models.CharField(choices=[('SELECTED', 'Selected'), ('ACTIVE', 'Active'), ('BOSS_READY', 'Boss Ready'), ('BOSS_ACTIVE', 'Boss Active'), ('CLEARED', 'Cleared'), ('FAILED', 'Failed')], default='SELECTED', max_length=20),
        ),
        migrations.CreateModel(
            name='DungeonRunRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=150)),
                ('room_type', models.CharField(choices=[('TRAP', 'Trap Room'), ('COMBAT', 'Combat Room'), ('TREASURE', 'Treasure Room'), ('SPECIAL', 'Special Room'), ('BOSS', 'Boss Room')], max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(default=3)),
                ('flavor_text', models.TextField(blank=True)),
                ('failure_text', models.TextField(blank=True)),
                ('damage_on_failure', models.PositiveIntegerField(blank=True, null=True)),
                ('is_cleared', models.BooleanField(default=False)),
                ('grid_row', models.PositiveSmallIntegerField(default=1)),
                ('grid_col', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_rooms', to='fantasy_roles.partydungeonrun')),
            ],
            options={
                'ordering': ['run', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='DungeonRunConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_connections', to='fantasy_roles.partydungeonrun')),
                ('from_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_connections_from', to='fantasy_roles.dungeonrunroom')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_connections_to', to='fantasy_roles.dungeonrunroom')),
            ],
            options={
                'ordering': ['run', 'from_room__room_number', 'to_room__room_number'],
            },
        ),

        migrations.RunPython(
            clear_existing_run_current_rooms,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='partydungeonrun',
            name='current_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_party_runs', to='fantasy_roles.dungeonrunroom'),
        ),
        migrations.AddConstraint(
            model_name='dungeonrunroom',
            constraint=models.UniqueConstraint(fields=('run', 'room_number'), name='unique_generated_room_number_per_run'),
        ),
        migrations.AddConstraint(
            model_name='dungeonrunconnection',
            constraint=models.UniqueConstraint(fields=('from_room', 'to_room'), name='unique_generated_room_connection'),
        ),
    ]
