# Generated by Django 6.0.6 on 2026-06-24 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0006_dungeon_combat_room_count_dungeon_special_room_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DungeonRoomTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('room_type', models.CharField(choices=[('TRAP', 'Trap Room'), ('COMBAT', 'Combat Room'), ('TREASURE', 'Treasure Room'), ('SPECIAL', 'Special Room')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_templates/')),
                ('difficulty', models.PositiveSmallIntegerField(default=3, help_text='Use a value from 1 to 5.')),
                ('flavor_text', models.TextField(blank=True, help_text='Description or hint shown to players.')),
                ('failure_text', models.TextField(blank=True, help_text='What happens when players fail.')),
                ('damage_on_failure', models.PositiveIntegerField(blank=True, help_text='Optional explicit damage. Useful for combat rooms.', null=True)),
                ('is_mimic_room', models.BooleanField(default=False, help_text='Mark this if the special room is a mimic encounter.')),
                ('is_active', models.BooleanField(default=True)),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_templates', to='fantasy_roles.dungeon')),
            ],
            options={
                'ordering': ['dungeon', 'room_type', 'difficulty', 'name'],
            },
        ),
        migrations.AddField(
            model_name='dungeonrunroom',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_run_rooms', to='fantasy_roles.dungeonroomtemplate'),
        ),
        migrations.CreateModel(
            name='ItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('scope', models.CharField(choices=[('GLOBAL', 'Global'), ('DUNGEON_SPECIFIC', 'Dungeon-specific')], default='GLOBAL', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('effect_text', models.TextField()),
                ('roll_number', models.PositiveSmallIntegerField(blank=True, help_text='Optional number needed to obtain this item from a chest.', null=True)),
                ('is_consumable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dungeon', models.ForeignKey(blank=True, help_text='Leave blank if this item can appear in any dungeon.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_templates', to='fantasy_roles.dungeon')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartyInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('obtained_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_inventory_entries', to='fantasy_roles.itemtemplate')),
                ('obtained_in_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_obtained_here', to='fantasy_roles.dungeonrunroom')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='fantasy_roles.adventuringparty')),
            ],
            options={
                'ordering': ['item__name'],
                'constraints': [models.UniqueConstraint(fields=('party', 'item'), name='unique_item_per_party_inventory')],
            },
        ),
    ]
