# Generated by Django 6.0.6 on 2026-06-24 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0007_dungeonroomtemplate_dungeonrunroom_source_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('TRAP_ACTION', 'Trap Action'), ('BASIC_ATTACK', 'Basic Attack'), ('OPEN_CHEST', 'Open Chest'), ('LEAVE_TREASURE', 'Leave Treasure'), ('SPECIAL_ACTION', 'Special Action')], max_length=30)),
                ('action_text', models.TextField(blank=True)),
                ('die_roll', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('difficulty_at_roll', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('damage_taken', models.PositiveIntegerField(default=0)),
                ('result_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_attempts', to='fantasy_roles.playercharacter')),
                ('item_awarded', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_attempts_awarded', to='fantasy_roles.itemtemplate')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='fantasy_roles.dungeonrunroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
