# Generated by Django 6.0.6 on 2026-06-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0008_roomattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='classskill',
            name='can_use_in_combat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classskill',
            name='can_use_in_special',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classskill',
            name='can_use_in_trap',
            field=models.BooleanField(default=False, help_text='Usually false. Trap rooms normally require written actions.'),
        ),
        migrations.AddField(
            model_name='classskill',
            name='roll_bonus',
            field=models.PositiveSmallIntegerField(default=0, help_text='Bonus added to the die roll when this skill is used.'),
        ),
    ]
