# Generated by Django 6.0.6 on 2026-06-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0009_classskill_can_use_in_combat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomattempt',
            name='action_type',
            field=models.CharField(choices=[('TRAP_ACTION', 'Trap Action'), ('BASIC_ATTACK', 'Basic Attack'), ('SKILL', 'Skill'), ('OPEN_CHEST', 'Open Chest'), ('LEAVE_TREASURE', 'Leave Treasure'), ('SPECIAL_ACTION', 'Special Action')], max_length=30),
        ),
    ]
