# Generated by Django 6.0.6 on 2026-06-25 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0010_alter_roomattempt_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomattempt',
            name='final_roll_total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomattempt',
            name='roll_bonus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomattempt',
            name='skill_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_attempts', to='fantasy_roles.classskill'),
        ),
    ]
