# Generated by Django 6.0.6 on 2026-06-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0011_roomattempt_final_roll_total_roomattempt_roll_bonus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classskill',
            options={},
        ),
        migrations.AddField(
            model_name='classskill',
            name='skill_scope',
            field=models.CharField(choices=[('ROOM', 'Room Skill'), ('BOSS', 'Boss Skill')], default='ROOM', max_length=20),
        ),
        migrations.AlterField(
            model_name='classskill',
            name='ap_cost',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='classskill',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
