# Generated by Django 6.0.6 on 2026-06-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0012_alter_classskill_options_classskill_skill_scope_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classskill',
            name='can_use_in_combat',
        ),
        migrations.RemoveField(
            model_name='classskill',
            name='can_use_in_special',
        ),
        migrations.RemoveField(
            model_name='classskill',
            name='can_use_in_trap',
        ),
        migrations.RemoveField(
            model_name='classskill',
            name='roll_bonus',
        ),
        migrations.RemoveField(
            model_name='classskill',
            name='skill_scope',
        ),
    ]
