# Generated by Django 6.0.6 on 2026-06-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0014_classskill_can_use_in_combat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classweakness',
            options={},
        ),
        migrations.AddField(
            model_name='classskill',
            name='can_use_in_treasure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classskill',
            name='duration_turns',
            field=models.PositiveSmallIntegerField(default=0, help_text='Used mostly for boss effects.'),
        ),
        migrations.AddField(
            model_name='classskill',
            name='effect_code',
            field=models.CharField(choices=[('NONE', 'No Special Effect'), ('ROOM_REDUCE_DIFFICULTY', 'Reduce room difficulty'), ('ROOM_ROLL_BONUS', 'Add bonus to room roll'), ('ROOM_REDUCE_FAILURE_DAMAGE', 'Reduce failure damage'), ('ROOM_REROLL_AFTER_FAIL', 'Reroll after failed room roll'), ('ROOM_RANDOM_ROLL_BONUS', 'Random bonus before roll'), ('ROOM_RECOVER_LIFE_ON_SUCCESS', 'Recover life on success'), ('ROOM_FIELD_AID', 'Reduce another player’s failure damage'), ('BOSS_DAMAGE_OVER_TIME', 'Boss damage over time'), ('BOSS_DAMAGE_BUFF', 'Boss damage buff'), ('BOSS_SKIP_TURN', 'Boss skips turn'), ('BOSS_PARTY_DAMAGE_BUFF', 'Party damage buff'), ('BOSS_TAUNT', 'Force boss to target user'), ('BOSS_DOUBLE_ATTACK', 'Attack twice'), ('BOSS_PARTY_SHIELD', 'Party shield'), ('BOSS_FIXED_DAMAGE', 'Fixed boss damage'), ('BOSS_UNTARGETABLE', 'User cannot be attacked'), ('BOSS_RESTORE_AP', 'Restore AP'), ('BOSS_HEAL', 'Restore life'), ('BOSS_D6_DAMAGE', 'Deal d6 damage'), ('BOSS_D6_PLUS_DAMAGE', 'Deal d6 plus damage'), ('BOSS_LIFESTEAL', 'Lifesteal effect')], default='NONE', max_length=60),
        ),
        migrations.AddField(
            model_name='classskill',
            name='effect_value',
            field=models.SmallIntegerField(default=0, help_text='Main numeric value for the effect, such as +2, -1, or 5 healing.'),
        ),
        migrations.AddField(
            model_name='classskill',
            name='secondary_value',
            field=models.SmallIntegerField(default=0, help_text='Optional second value, such as d6 + 2 or damage reduction.'),
        ),
        migrations.AddField(
            model_name='classweakness',
            name='duration_turns',
            field=models.PositiveSmallIntegerField(default=0, help_text='Used mostly for boss weaknesses.'),
        ),
        migrations.AddField(
            model_name='classweakness',
            name='effect_code',
            field=models.CharField(choices=[('NONE', 'No Special Effect'), ('ROOM_EXTRA_TRAP_FAIL_DAMAGE', 'Extra damage on failed Trap Room'), ('ROOM_EXTRA_COMBAT_FAIL_DAMAGE', 'Extra damage on failed Combat Room'), ('ROOM_TRAP_ROLL_PENALTY', 'Penalty on Trap Room rolls'), ('ROOM_COMBAT_ROLL_PENALTY', 'Penalty on Combat Room rolls'), ('ROOM_EXTRA_DAMAGE_AFTER_SKILL_FAIL', 'Extra damage after failed skill roll'), ('ROOM_NEXT_SKILL_COST_AFTER_FAIL', 'Next room skill costs more after fail'), ('ROOM_LOSE_AP_ON_LOW_NATURAL_ROLL', 'Lose AP on low natural roll'), ('ROOM_SKILLS_COST_LIFE', 'Room skills cost life instead of AP'), ('BOSS_EXTRA_DAMAGE_TAKEN', 'Extra boss damage taken'), ('BOSS_AFTER_SKILL_EXTRA_DAMAGE', 'Extra damage after using skill'), ('BOSS_CANNOT_REPEAT_SKILL', 'Cannot repeat same skill'), ('BOSS_FAILED_ROLL_BACKLASH', 'Failed roll backlash'), ('BOSS_ATTACK_DIFFICULTY_UP', 'Boss difficulty up for attacks'), ('BOSS_CONSECUTIVE_SKILL_COST_UP', 'Consecutive skill cost up'), ('BOSS_LOW_ROLL_SELF_DAMAGE', 'Low roll self damage'), ('BOSS_SKILLS_COST_LIFE', 'Boss skills cost life instead of AP')], default='NONE', max_length=70),
        ),
        migrations.AddField(
            model_name='classweakness',
            name='effect_value',
            field=models.SmallIntegerField(default=0, help_text='Main numeric value for the weakness, such as +1 damage or -1 roll.'),
        ),
        migrations.AddField(
            model_name='classweakness',
            name='secondary_value',
            field=models.SmallIntegerField(default=0, help_text='Optional second value.'),
        ),
        migrations.AddField(
            model_name='classweakness',
            name='weakness_scope',
            field=models.CharField(choices=[('ROOM', 'Room Weakness'), ('BOSS', 'Boss Weakness')], default='ROOM', max_length=20),
        ),
        migrations.AlterField(
            model_name='classskill',
            name='roll_bonus',
            field=models.PositiveSmallIntegerField(default=0, help_text='Direct bonus added to a die roll, if applicable.'),
        ),
        migrations.AlterField(
            model_name='classweakness',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
