# Generated by Django 6.0.6 on 2026-06-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0015_alter_classweakness_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercharacter',
            name='room_skill_ap_penalty',
            field=models.PositiveSmallIntegerField(default=0, help_text='Temporary AP penalty applied to the next room skill.'),
        ),
        migrations.AlterField(
            model_name='roomattempt',
            name='roll_bonus',
            field=models.SmallIntegerField(default=0),
        ),
    ]
