# Generated by Django 6.0.6 on 2026-06-25 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0016_playercharacter_room_skill_ap_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partydungeonrun',
            name='current_turn_character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_turn_runs', to='fantasy_roles.playercharacter'),
        ),
        migrations.AddField(
            model_name='partydungeonrun',
            name='turn_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
