# Generated by Django 6.0.6 on 2026-06-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0017_partydungeonrun_current_turn_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partydungeonrun',
            name='failure_reason',
            field=models.CharField(choices=[('NONE', 'No failure'), ('PARTY_DEFEATED', 'The party was defeated'), ('OUT_OF_AP', 'The party ran out of AP')], default='NONE', max_length=30),
        ),
    ]
