# Generated by Django 6.0.6 on 2026-06-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0018_partydungeonrun_failure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeonrunroom',
            name='challenge_round',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roomattempt',
            name='challenge_round',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
