# Generated by Django 6.0.6 on 2026-06-25 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0019_dungeonrunroom_challenge_round_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('phase', models.CharField(choices=[('NORMAL', 'Normal Form'), ('RAGE', 'Rage Form'), ('BOTH', 'Both Forms')], default='NORMAL', max_length=20)),
                ('slot', models.CharField(choices=[('FIRST', 'First Ability'), ('SECOND', 'Second Ability')], max_length=20)),
                ('effect_code', models.CharField(choices=[('NONE', 'No Special Effect'), ('DAMAGE_LOWEST_LIFE', 'Damage player with lowest life'), ('PARALYZE_HIGHEST_ATTACK', 'Paralyze player with highest attack'), ('WEAKEN_HIGHEST_ATTACK', 'Highest attack player deals limited damage'), ('DAMAGE_RANDOM_AND_SKIP', 'Damage random player and skip their action'), ('DAMAGE_PARTY_D6_PLUS', 'Deal d6 plus value damage to party'), ('DAMAGE_RANDOM_AND_PARALYZE', 'Damage random player and paralyze'), ('PARTY_SKIP_AND_RANDOM_DAMAGE', 'Party skips action and random player takes damage'), ('SELF_HEAL', 'Boss heals itself'), ('DAMAGE_RANDOM_CANNOT_ATTACK', 'Damage random player and prevent attacking'), ('PARTY_PARALYZE_AND_DAMAGE_TAKEN_UP', 'Paralyze party and increase next boss damage'), ('DAMAGE_RANDOM_AND_PARTY_CANNOT_ATTACK', 'Damage random player and party cannot attack'), ('DAMAGE_ALL_PLAYERS', 'Damage all players'), ('DAMAGE_RANDOM_PLAYER', 'Damage random player'), ('DAMAGE_TRANSFORMER', 'Damage player who triggered transformation'), ('BOSS_UNTARGETABLE_THEN_DAMAGE_HIGHEST_LIFE', 'Boss cannot be attacked, then damages highest life player')], default='NONE', max_length=80)),
                ('effect_value', models.SmallIntegerField(default=0, help_text='Main value, such as damage, healing, or damage limit.')),
                ('secondary_value', models.SmallIntegerField(default=0, help_text='Optional second value, such as d6 bonus or failed roll penalty.')),
                ('duration_turns', models.PositiveSmallIntegerField(default=0, help_text='How long the effect lasts.')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['boss', 'phase', 'slot', 'order'],
            },
        ),
        migrations.CreateModel(
            name='BossEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WON', 'Won'), ('LOST', 'Lost')], default='ACTIVE', max_length=20)),
                ('phase', models.CharField(choices=[('NORMAL', 'Normal'), ('RAGE', 'Rage')], default='NORMAL', max_length=20)),
                ('current_life', models.PositiveIntegerField()),
                ('current_actor', models.CharField(choices=[('BOSS', 'Boss'), ('PLAYER', 'Player')], default='BOSS', max_length=20)),
                ('next_boss_ability_slot', models.CharField(choices=[('FIRST', 'First Ability'), ('SECOND', 'Second Ability')], default='FIRST', max_length=20)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('player_phase_number', models.PositiveIntegerField(default=0, help_text='Increments after each boss action. Used to track which players acted.')),
                ('has_transformed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_turn_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_boss_turns', to='fantasy_roles.playercharacter')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boss_encounter', to='fantasy_roles.partydungeonrun')),
                ('transformed_by_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_boss_transformations', to='fantasy_roles.playercharacter')),
            ],
        ),
        migrations.CreateModel(
            name='BossCombatEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('PLAYER', 'Player'), ('PARTY', 'Party'), ('BOSS', 'Boss')], max_length=20)),
                ('effect_code', models.CharField(choices=[('PLAYER_SKIP_TURN', 'Player skips turn'), ('PLAYER_CANNOT_ATTACK', 'Player cannot attack'), ('PLAYER_DAMAGE_DEALT_OVERRIDE', 'Player damage is overridden'), ('PLAYER_EXTRA_DAMAGE_ON_FAILED_THROW', 'Extra damage on failed throw'), ('PARTY_SKIP_TURN', 'Party skips turn'), ('PARTY_CANNOT_ATTACK', 'Party cannot attack'), ('PARTY_EXTRA_BOSS_DAMAGE_TAKEN', 'Party receives extra boss damage'), ('BOSS_UNTARGETABLE', 'Boss cannot be attacked'), ('BOSS_PENDING_DAMAGE_HIGHEST_LIFE', 'Boss will damage highest life player')], max_length=80)),
                ('value', models.SmallIntegerField(default=0)),
                ('secondary_value', models.SmallIntegerField(default=0)),
                ('remaining_turns', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_ability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_effects', to='fantasy_roles.bossability')),
                ('target_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boss_combat_effects', to='fantasy_roles.playercharacter')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combat_effects', to='fantasy_roles.bossencounter')),
            ],
        ),
        migrations.CreateModel(
            name='BossActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('BOSS', 'Boss'), ('PLAYER', 'Player'), ('SYSTEM', 'System')], max_length=20)),
                ('action_type', models.CharField(choices=[('BOSS_ABILITY', 'Boss Ability'), ('BASIC_ATTACK', 'Basic Attack'), ('BOSS_SKILL', 'Boss Skill'), ('PASS', 'Pass'), ('TRANSFORMATION', 'Transformation'), ('VICTORY', 'Victory'), ('DEFEAT', 'Defeat')], max_length=30)),
                ('phase', models.CharField(choices=[('NORMAL', 'Normal'), ('RAGE', 'Rage')], default='NORMAL', max_length=20)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('player_phase_number', models.PositiveIntegerField(default=0)),
                ('die_roll', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('final_roll_total', models.SmallIntegerField(blank=True, null=True)),
                ('difficulty_at_roll', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('damage_to_boss', models.PositiveIntegerField(default=0)),
                ('damage_to_players', models.PositiveIntegerField(default=0)),
                ('healing_done', models.PositiveIntegerField(default=0)),
                ('result_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boss_ability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='fantasy_roles.bossability')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boss_action_logs', to='fantasy_roles.playercharacter')),
                ('player_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boss_action_logs', to='fantasy_roles.classskill')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='fantasy_roles.bossencounter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BossTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_name', models.CharField(max_length=120)),
                ('rage_name', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bosses/')),
                ('rage_image', models.ImageField(blank=True, null=True, upload_to='bosses/rage/')),
                ('phase_one_life', models.PositiveIntegerField(default=30)),
                ('phase_two_life', models.PositiveIntegerField(default=15)),
                ('phase_one_difficulty', models.PositiveSmallIntegerField(default=3)),
                ('phase_two_difficulty', models.PositiveSmallIntegerField(default=4)),
                ('transformation_name', models.CharField(blank=True, help_text="Example: Goethia's Mask, Cool Down, Chain the Beast.", max_length=120)),
                ('intro_text', models.TextField(blank=True)),
                ('transformation_text', models.TextField(blank=True)),
                ('victory_text', models.TextField(blank=True)),
                ('defeat_text', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dungeon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boss_template', to='fantasy_roles.dungeon')),
            ],
        ),
        migrations.AddField(
            model_name='bossencounter',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='fantasy_roles.bosstemplate'),
        ),
        migrations.AddField(
            model_name='bossability',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='fantasy_roles.bosstemplate'),
        ),
    ]
