# Generated by Django 6.0.6 on 2026-06-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0020_bossability_bossencounter_bosscombateffect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeonroomtemplate',
            name='mimic_image',
            field=models.ImageField(blank=True, null=True, upload_to='fantasy_roles/rooms/mimics/'),
        ),
    ]
