# Generated by Django 6.0.6 on 2026-06-27 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0021_dungeonroomtemplate_mimic_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSupportEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_code', models.CharField(choices=[('NONE', 'No Special Effect'), ('ROOM_REDUCE_DIFFICULTY', 'Reduce room difficulty'), ('ROOM_ROLL_BONUS', 'Add bonus to room roll'), ('ROOM_REDUCE_FAILURE_DAMAGE', 'Reduce failure damage'), ('ROOM_REROLL_AFTER_FAIL', 'Reroll after failed room roll'), ('ROOM_RANDOM_ROLL_BONUS', 'Random bonus before roll'), ('ROOM_RECOVER_LIFE_ON_SUCCESS', 'Recover life on success'), ('ROOM_FIELD_AID', 'Reduce another player’s failure damage'), ('BOSS_DAMAGE_OVER_TIME', 'Boss damage over time'), ('BOSS_DAMAGE_BUFF', 'Boss damage buff'), ('BOSS_SKIP_TURN', 'Boss skips turn'), ('BOSS_PARTY_DAMAGE_BUFF', 'Party damage buff'), ('BOSS_TAUNT', 'Force boss to target user'), ('BOSS_DOUBLE_ATTACK', 'Attack twice'), ('BOSS_PARTY_SHIELD', 'Party shield'), ('BOSS_FIXED_DAMAGE', 'Fixed boss damage'), ('BOSS_UNTARGETABLE', 'User cannot be attacked'), ('BOSS_RESTORE_AP', 'Restore AP'), ('BOSS_HEAL', 'Restore life'), ('BOSS_D6_DAMAGE', 'Deal d6 damage'), ('BOSS_D6_PLUS_DAMAGE', 'Deal d6 plus damage'), ('BOSS_LIFESTEAL', 'Lifesteal effect')], max_length=60)),
                ('effect_value', models.SmallIntegerField(default=0)),
                ('secondary_value', models.SmallIntegerField(default=0)),
                ('uses_remaining', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_effects', to='fantasy_roles.dungeonrunroom')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_support_effects', to='fantasy_roles.classskill')),
                ('source_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_support_effects_created', to='fantasy_roles.playercharacter')),
                ('target_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_support_effects_received', to='fantasy_roles.playercharacter')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
