# Generated by Django 6.0.6 on 2026-06-27 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0022_roomsupporteffect'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeonroom',
            name='is_mimic_room',
            field=models.BooleanField(default=False, help_text='Mark this if this room begins as a special room but becomes a mimic encounter.'),
        ),
        migrations.AddField(
            model_name='dungeonroom',
            name='mimic_image',
            field=models.ImageField(blank=True, null=True, upload_to='dungeon_rooms/mimics/'),
        ),
        migrations.AddField(
            model_name='dungeonrunroom',
            name='source_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_run_rooms', to='fantasy_roles.dungeonroom'),
        ),
    ]
