# Generated by Django 6.0.6 on 2026-06-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0023_dungeonroom_is_mimic_room_dungeonroom_mimic_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='icon_key',
            field=models.CharField(blank=True, default='', help_text='PNG icon filename without extension. Example: assassin, bard, wizard.', max_length=60),
        ),
    ]
