# Generated by Django 6.0.6 on 2026-06-30 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0024_characterclass_icon_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossactionlog',
            name='player_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boss_action_logs', to='fantasy_roles.itemtemplate'),
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='can_use_in_boss',
            field=models.BooleanField(default=True, help_text='Can be used during boss combat.'),
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='can_use_in_rooms',
            field=models.BooleanField(default=True, help_text='Can be used while exploring dungeon rooms.'),
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='effect_code',
            field=models.CharField(choices=[('NONE', 'No special effect'), ('HEAL_PARTY', 'Heal all living party members'), ('HEAL_SELF', 'Heal current character'), ('RESTORE_AP_PARTY', 'Restore AP to all living party members'), ('RESTORE_AP_SELF', 'Restore AP to current character'), ('DAMAGE_BOSS', 'Deal fixed damage to boss'), ('D6_DAMAGE_BOSS', 'Deal d6 damage to boss'), ('REVIVE_LOWEST', 'Revive one defeated party member')], default='NONE', max_length=40),
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='effect_value',
            field=models.SmallIntegerField(default=0, help_text='Main value, such as healing amount, AP restored, or boss damage.'),
        ),
        migrations.AddField(
            model_name='itemtemplate',
            name='secondary_value',
            field=models.SmallIntegerField(default=0, help_text='Optional second value for later item effects.'),
        ),
        migrations.AddField(
            model_name='roomattempt',
            name='item_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_attempts_used', to='fantasy_roles.itemtemplate'),
        ),
        migrations.AlterField(
            model_name='bossactionlog',
            name='action_type',
            field=models.CharField(choices=[('BOSS_ABILITY', 'Boss Ability'), ('BASIC_ATTACK', 'Basic Attack'), ('BOSS_SKILL', 'Boss Skill'), ('ITEM_USE', 'Use Item'), ('PASS', 'Pass'), ('TRANSFORMATION', 'Transformation'), ('VICTORY', 'Victory'), ('DEFEAT', 'Defeat')], max_length=30),
        ),
        migrations.AlterField(
            model_name='roomattempt',
            name='action_type',
            field=models.CharField(choices=[('TRAP_ACTION', 'Trap Action'), ('BASIC_ATTACK', 'Basic Attack'), ('SKILL', 'Skill'), ('OPEN_CHEST', 'Open Chest'), ('LEAVE_TREASURE', 'Leave Treasure'), ('SPECIAL_ACTION', 'Special Action'), ('USE_ITEM', 'Use Item')], max_length=30),
        ),
    ]
