# Generated by Django 6.0.6 on 2026-06-30 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0025_bossactionlog_player_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtemplate',
            name='secondary_value',
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='can_use_in_boss',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='can_use_in_rooms',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='effect_code',
            field=models.CharField(choices=[('NONE', 'No special effect'), ('HEAL_PARTY', 'Restore Life to party'), ('RESTORE_AP_PARTY', 'Restore AP to party'), ('PERMANENT_ROLL_BONUS', 'Permanent roll bonus'), ('CLEAR_TRAP_ROOM', 'Automatically clear trap room'), ('REVIVE_MEMBER', 'Revive a defeated party member'), ('RUN_DAMAGE_REDUCTION', 'Reduce damage for the run')], default='NONE', max_length=40),
        ),
        migrations.AlterField(
            model_name='itemtemplate',
            name='effect_value',
            field=models.SmallIntegerField(default=0, help_text='Main value, such as +2 roll bonus, 10 healing, or 2 damage reduction.'),
        ),
        migrations.CreateModel(
            name='ItemRunEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_code', models.CharField(choices=[('NONE', 'No special effect'), ('HEAL_PARTY', 'Restore Life to party'), ('RESTORE_AP_PARTY', 'Restore AP to party'), ('PERMANENT_ROLL_BONUS', 'Permanent roll bonus'), ('CLEAR_TRAP_ROOM', 'Automatically clear trap room'), ('REVIVE_MEMBER', 'Revive a defeated party member'), ('RUN_DAMAGE_REDUCTION', 'Reduce damage for the run')], max_length=40)),
                ('value', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_effects', to='fantasy_roles.itemtemplate')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_effects', to='fantasy_roles.partydungeonrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
