# Generated by Django 6.0.6 on 2026-06-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0026_remove_itemtemplate_secondary_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomattempt',
            name='roll_breakdown',
            field=models.JSONField(blank=True, default=list, help_text="Named roll modifiers for UI animation. Example: [{'label': 'Lucky Charm', 'value': 2}]"),
        ),
    ]
