# Generated by Django 6.0.6 on 2026-06-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0027_roomattempt_roll_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossactionlog',
            name='damage_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bossactionlog',
            name='difficulty_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bossactionlog',
            name='roll_breakdown',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='roomattempt',
            name='damage_breakdown',
            field=models.JSONField(blank=True, default=list, help_text="Named damage reductions or increases for UI animation. Example: [{'label': 'Protection Ring', 'value': -2}]"),
        ),
        migrations.AddField(
            model_name='roomattempt',
            name='difficulty_breakdown',
            field=models.JSONField(blank=True, default=list, help_text="Named difficulty changes for UI animation. Example: [{'label': 'Arcane Insight', 'value': -2, 'from': 5, 'to': 3}]"),
        ),
    ]
