# Generated by Django 6.0.6 on 2026-06-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0028_bossactionlog_damage_breakdown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bosscombateffect',
            name='effect_code',
            field=models.CharField(choices=[('PLAYER_SKIP_TURN', 'Player skips turn'), ('PLAYER_CANNOT_ATTACK', 'Player cannot attack'), ('PLAYER_DAMAGE_DEALT_OVERRIDE', 'Player damage is overridden'), ('PLAYER_EXTRA_DAMAGE_ON_FAILED_THROW', 'Extra damage on failed throw'), ('PARTY_SKIP_TURN', 'Party skips turn'), ('PARTY_CANNOT_ATTACK', 'Party cannot attack'), ('PARTY_EXTRA_BOSS_DAMAGE_TAKEN', 'Party receives extra boss damage'), ('PARTY_DAMAGE_REDUCTION', 'Party damage reduction'), ('BOSS_UNTARGETABLE', 'Boss cannot be attacked'), ('BOSS_PENDING_DAMAGE_HIGHEST_LIFE', 'Boss will damage highest life player')], max_length=80),
        ),
    ]
