# Generated by Django 6.0.6 on 2026-07-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0029_alter_bosscombateffect_effect_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossactionlog',
            name='roll_sequence',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
