# Generated by Django 6.0.6 on 2026-07-02 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_roles', '0031_alter_bosscombateffect_effect_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossactionlog',
            name='production_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bossactionlog',
            name='production_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roomattempt',
            name='production_prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='roomattempt',
            name='production_response',
            field=models.TextField(blank=True),
        ),
    ]
